
// This file has been generated by genreflex with the --capabilities option
static  const char* clnames[] = {
//--Begin tmp/slc6_amd64_gcc491/src/PhysicsTools/PatUtils/src/PhysicsToolsPatUtils/a/PhysicsToolsPatUtils_xr.cc_tmp
 "LCGReflex/pat::DiObjectProxy",
//--End   tmp/slc6_amd64_gcc491/src/PhysicsTools/PatUtils/src/PhysicsToolsPatUtils/a/PhysicsToolsPatUtils_xr.cc_tmp
//--Final End
};

extern "C" void SEAL_CAPABILITIES (const char**& names, int& n )
{
names = clnames;
n = sizeof(clnames)/sizeof(char*);
}
